name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.6
            pep-425-tag: 'cp36-cp36m'
          - python-version: 3.7
            pep-425-tag: 'cp37-cp37m'
          - python-version: 3.8
            pep-425-tag: 'cp38-cp38'
          - python-version: 3.9
            pep-425-tag: 'cp39-cp39'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
      with:
        path: test_action
    - name: Checkout hello_py dummy project
      uses: actions/checkout@v2
      with:
        repository: ralfg/hello_py
        ref: v0.1.0
        path: hello_py
    - name: Build manylinux Python wheels
      uses: './test_action'
      with:
        python-versions: ${{ matrix.pep-425-tag }}
        build-requirements: 'setuptools numpy cython'
        system-packages: 'lrzip-devel zlib-devel'
        pre-build-command: 'echo Hello world! Testing pre-build command'
        package-path: 'hello_py'
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install wheel
      run: 'pip install hello_py/dist/hello_py*-manylinux1_x86_64.whl'
    - name: Test wheel
      run: 'hello_py'
